version: "3"

tasks:
  bootstrap:
    cmds:
      - kubectl create namespace argocd --dry-run=client --output=yaml | kubectl apply -f -
      - task: bootstrap:argocd
      - task: bootstrap:root

  bootstrap:argocd:
    internal: true
    dir: bootstrap/argocd
    cmds:
      - ./apply.sh

  bootstrap:root:
    internal: true
    dir: bootstrap/root
    cmds:
      - ./apply.sh

  dev:
    dir: dev
    cmds:
      - k3d cluster create sandman -p 8888:80@loadbalancer -v /etc/machine-id:/etc/machine-id:ro -v /var/log/journal:/var/log/journal:ro -v /var/run/docker.sock:/var/run/docker.sock --k3s-arg '--disable=traefik@server:0' --agents 0
      - k3d kubeconfig get sandman > kubeconfig-dev.yaml
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - helm install ingress-nginx ingress-nginx/ingress-nginx -n ingress-nginx --create-namespace --set controller.publishService.enabled=true
      - task: bootstrap

  dev:cleanup:
    cmds:
      - k3d cluster delete sandman

  scripts:argocd-admin-password:
    cmds:
      - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d



